apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certificate.issuer }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  isCA: true
  commonName: {{ .Values.certificate.name }}
  secretName: {{ .Values.certificate.name }}
  subject:
    organizations:
      - "Craig Miller"
    organizationalUnits:
      - MongoDB
    countries:
      - US
    states:
      - FL
  dnsNames:
    - craigmiller160.us
    - craigpc
    - mongodb.infra-prod
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Values.certificate.issuer }}
    kind: ClusterIssuer
    group: cert-manager.io