apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.deployment.name }}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 47.196.14.245/32
      ports:
        - protocol: TCP
          port: 27017
    - from:
        - ipBlock:
            cidr: 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 27017